CREATE USER AULA2_HOMEWORK1 IDENTIFIED BY oracle;
GRANT CONNECT TO AULA2_HOMEWORK1;
GRANT CONNECT, RESOURCE, DBA TO AULA2_HOMEWORK1;
GRANT CREATE SESSION TO AULA2_HOMEWORK1;
GRANT DBA TO AULA2_HOMEWORK1;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to AULA2_HOMEWORK1;
GRANT UNLIMITED TABLESPACE TO AULA2_HOMEWORK1;
GRANT CREATE MATERIALIZED VIEW TO AULA2_HOMEWORK1;
GRANT CREATE TABLE TO AULA2_HOMEWORK1;
GRANT GLOBAL QUERY REWRITE TO AULA2_HOMEWORK1;
GRANT SELECT ANY TABLE TO AULA2_HOMEWORK1;


--TABLES
CREATE TABLE AULA2_HOMEWORK1.PAIS ( 
ID_PAIS INT PRIMARY KEY NOT NULL,
NOME VARCHAR2(50) UNIQUE NOT NULL 
); 


CREATE TABLE AULA2_HOMEWORK1.ESTADO( 
ID_ESTADO INT PRIMARY KEY NOT NULL,
ID_PAIS INT NOT NULL, 
NOME VARCHAR2(50) UNIQUE NOT NULL, 
CONSTRAINT FK_ID_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES AULA2_HOMEWORK1.PAIS( ID_PAIS ) 
);

CREATE TABLE AULA2_HOMEWORK1.CIDADE(
ID_CIDADE INT NOT NULL,
ID_ESTADO INT NOT NULL,
NOME VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CIDADE_ESTADO PRIMARY KEY (ID_CIDADE, ID_ESTADO)
);


CREATE TABLE AULA2_HOMEWORK1.BAIRRO (
ID_BAIRRO NUMBER(38,0) NOT NULL,
ID_CIDADE NUMBER(38,0) NOT NULL,
ID_ESTADO NUMBER (38,0) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
CONSTRAINT PK_BAIRRO_CIDADE PRIMARY KEY (ID_BAIRRO , ID_CIDADE),
CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES AULA2_HOMEWORK1.ESTADO (ID_ESTADO)
);


CREATE TABLE AULA2_HOMEWORK1.ENDERECO(
ID_ENDERECO INT PRIMARY KEY NOT NULL,
ID_CIDADE INT NOT NULL,
ID_BAIRRO INT NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR2(100),
CEP CHAR(9),
CONSTRAINT FK_ID_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES AULA2_HOMEWORK1.BAIRRO (ID_BAIRRO, ID_CIDADE)
);



--SEQS
CREATE SEQUENCE SEQ_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CIDADE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


--INSERTS
INSERT INTO AULA2_HOMEWORK1.PAIS (ID_PAIS, NOME) VALUES(SEQ_PAIS.nextval, 'Brasil');
INSERT INTO AULA2_HOMEWORK1.PAIS (ID_PAIS, NOME) VALUES(SEQ_PAIS.nextval, 'EUA');

INSERT INTO AULA2_HOMEWORK1.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.nextval, 1, 'RS');
INSERT INTO AULA2_HOMEWORK1.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.nextval, 1, 'SP');
INSERT INTO AULA2_HOMEWORK1.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.nextval, 2, 'CA');
INSERT INTO AULA2_HOMEWORK1.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.nextval, 2, 'FL');

INSERT INTO AULA2_HOMEWORK1.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.nextval, 1, 'Porto Alegre');
INSERT INTO AULA2_HOMEWORK1.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.nextval, 2, 'São Paulo');
INSERT INTO AULA2_HOMEWORK1.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.nextval, 3, 'Los Angeles');
INSERT INTO AULA2_HOMEWORK1.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.nextval, 4, 'Miami');

INSERT INTO AULA2_HOMEWORK1.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.nextval, 1, 1, 'Sarandi');
INSERT INTO AULA2_HOMEWORK1.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.nextval, 2, 2, 'Liberdade');
INSERT INTO AULA2_HOMEWORK1.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.nextval, 3, 3, 'Beverly Hills');
INSERT INTO AULA2_HOMEWORK1.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.nextval, 4, 4, 'Coconut Grove');

INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval , 1, 1, 'Rua A', 11, 'Apto 11', 000000011);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval , 1, 1, 'Rua B', 12, 'Apto 12', 000000012);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 2, 2, 'Rua C', 21, 'Apto 21', 000000021);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 2, 2, 'Rua D', 22, 'Apto 22', 000000022);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 3, 3, 'Street A', 31, 'Apto 31', 000000031);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 3, 3, 'Street B', 32, 'Apto 32', 000000032);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 4, 4, 'Street C', 41, 'Apto 41', 000000041);
INSERT INTO AULA2_HOMEWORK1.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.nextval, 4, 4, 'Street D', 42, 'Apto 42', 000000042);


--PAISES ORDEM DECRESCENTE
SELECT NOME  FROM AULA2_HOMEWORK1.PAIS
ORDER BY NOME DESC;

--LOGRADOURO E CEP COMEÇANDO POR A
SELECT LOGRADOURO, CEP FROM AULA2_HOMEWORK1.ENDERECO
WHERE LOWER(LOGRADOURO) LIKE 'a%'; 

--ENDERECOS CEP FINAL 0
SELECT * FROM AULA2_HOMEWORK1.ENDERECO 
WHERE CEP LIKE '%0';

--ENDERECO NUMERO 1 E 100
SELECT * FROM AULA2_HOMEWORK1.ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

--TODOS ENDERECOS QUE SAO RUA E CEP DECRESCENTE
SELECT * FROM AULA2_HOMEWORK1.ENDERECO
WHERE LOWER(LOGRADOURO) LIKE 'rua%'
ORDER BY CEP DESC; 

--QTD ENDERECOS
SELECT COUNT(ID_ENDERECO)
FROM AULA2_HOMEWORK1.ENDERECO;

--QTD ENDERECOS POR ID
SELECT ID_CIDADE, COUNT(ID_ENDERECO)
FROM AULA2_HOMEWORK1.ENDERECO
GROUP BY ID_CIDADE;
